Feature/joint controller interface
kroshu/ros2_kuka_sunrise pull request #19
Opened 2022-05-06 13:15 UTC by Svastits

Created an interface (JointControllerBase class) for joint_controller with all necessary members and functions to communicate with the sunrise driver.
The class inherits from ROS2BaseNode.

Child classes:
 - InterpolatingContoller: this has the same functionality, as the first JointController (subscribing to reference joint states and interpolating to the velocity limits)
 - RateScaledController (child of InterpolatingController): given a source with const rate for reference joint states, the interpolation is done so, that the motion of the robot finishes when the next reference arrives (if the max velocity allows this)

2022-05-06 16:28 UTC, kovacsge11 requested changes
Everything OK, minor remark on service interface.

2022-05-11 08:42 UTC, kovacsge11 approved these changes

2022-05-11 17:24 UTC, resizoltan commented
Can you please delete the `ParameterSetAccessRights` struct definition from `joint_controller_base.hpp`? It is already defined in the `ROS2BaseNode`.

2022-05-11 17:41 UTC, resizoltan commented on kuka_sunrise_control/robot_control/src/robot_control/rate_scaled_controller.cpp
> +        loopPeriod() / (8 * request->data)) + 1;
What is the magic number 8? Publish frequency of camera? If yes, this hidden dependency should be generalized out somehow.

2022-05-11 17:53 UTC, resizoltan commented on kuka_sunrise_control/robot_control/include/robot_control/rate_scaled_controller.hpp
> +class ScaledJointController : public InterpolatingController
What about
```suggestion
class RateScaledJointController : public InterpolatingController
```
?

2022-05-18 09:54 UTC, kovacsge11 commented
@resizoltan please re-review.

2022-05-24 09:06 UTC, resizoltan approved these changes

2022-05-25 07:53 UTC, merged